[global]

developmentMode = false

[logger]

level = "error"  # Reduz warnings

[client]

showSidebarNavigation = false
showErrorDetails = false

[server]

folderWatchBlacklist = ['']
fileWatcherType = "auto"
headless = true
runOnSave = false
address = "localhost"
port = 8504
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]

serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8504

# Configurações para reduzir warnings do Lighthouse
[theme]

base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"